# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np

#loading data set

df = pd.read_csv("cardio_train - cardio_train.csv", sep = ",")

# Coverting days to years
df["age_years"] = (df["age"]/ 365). round().astype(int)

# finding BMI - Weight or heigh alon not predictive, but heigh might be predictive of blood pressure
df["BMI"] = df["weight"] / (df["height"] * df["height"] / 10000)

#data cleaning BMI, HEIGHT, BP ETC
# Remove unrealistic blood pressure values
df.drop(df[(df['ap_hi'] > 250) |
            (df['ap_hi'] < 50)].index, inplace=True)

df.drop(df[(df['ap_lo'] > 140) |
            (df['ap_lo'] < 30)].index, inplace=True)

df.drop(df[(df['ap_hi'] < df['ap_lo']) |
            (df['ap_lo'] > df['ap_hi'].quantile(0.025))].index, inplace=True)

#Mean arterial pressure
df["MAP"] = (df["ap_hi"]) /3 + 2 * (df["ap_lo"]) / 3

import plotly.express as px

fig = px.scatter_3d(df, x='age_years', y='MAP', z='BMI',
              color='cardio')
fig.show()